/*
 * EXTI_Config.h
 *
 *      Author: NOUR ALAA ELDIN HANAFY MOHARRAM
 */

#ifndef MCAL_EXTI_EXTI_HEADER_EXTI_CONFIG_H_
#define MCAL_EXTI_EXTI_HEADER_EXTI_CONFIG_H_
/*Options"
 * 1-LOW_LEVEL
 * 2-ON_CHANGE
 * 3-FALLING_EDGE
 * 4-RISING_EDGE*/
#define INT0_SENSE        RISING_EDGE

/*1-ENABLE
 * 2-DISABLE
 */
#define INT0_INITIAL_STATE   ENABLE

#endif /* MCAL_EXTI_EXTI_HEADER_EXTI_CONFIG_H_ */
